include: package:very_good_analysis/analysis_options.yaml




# Lint kuralları etkinleştirilir.
linter:
  rules:
   public_member_api_docs: false
   lines_longer_than_80_chars: false
   sort_pub_dependencies: false

analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]
  errors:
    invalid_assignment: ignore
    non_constant_identifier_names: ignore
# Analizden hariç tutulacak dizinler belirlenir.

