name: togodo
description: A new Flutter project.
version: 1.0.8+71
publish_to: 'none' 



environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Google and Firebasef
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  flutter_facebook_auth: ^6.0.4
  twitter_login: ^4.4.2
  google_sign_in: ^6.1.0
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.1+1
  cloud_firestore: ^4.7.1
  sign_in_with_apple: ^5.0.0
  firebase_messaging: ^14.6.3
  # For Socket

  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.2

  # For Architecture
  flutter_hooks: ^0.20.2 
  hooks_riverpod: ^2.3.6

  # For Networking
  dio: ^5.3.2
  http: ^1.1.2
  retrofit: ^4.0.1

  # For User-Agent Client Hints
  ua_client_hints: ^1.1.3

  # For Model
  json_serializable: ^6.6.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  #For Dialog
  modal_bottom_sheet:
      git:  
        url: https://github.com/CoolDude53/modal_bottom_sheet.git  
        ref: main
        path: modal_bottom_sheet

  # For Navigation
  auto_route: ^7.8.4
  
  # For DateTime
  intl: ^0.18.0

  # Convert between Enum and String
  enum_to_string: ^2.0.1
  permission_handler: ^11.1.0

  # For Cache
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For Video
  video_player: ^2.6.1
  chewie: ^1.4.0
  video_editor: ^3.0.0
  ffmpeg_kit_flutter: ^6.0.3
  fraction: ^5.0.2

  # For Audio
  flutter_sound_record: ^3.3.2
  just_audio: ^0.9.36

  # For Image / Picker
  cached_network_image: ^3.3.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.8
  insta_assets_picker: ^2.2.1
  wechat_assets_picker: ^8.9.0-dev.1
  # For Architecture
  
  # For UIs
  flutter_svg: ^2.0.5
  kartal: ^3.3.0
  blur: ^3.1.0
  auto_size_text: ^3.0.0
  table_calendar: ^3.0.9
  swipe_to: ^1.0.5
  range_slider_flutter: ^0.0.2
  reorderables: ^0.6.0
  lottie: ^2.7.0
  card_swiper: ^3.0.1
  cropperx: ^1.1.1
  crop: ^0.5.5
  #connectivity_plus: ^4.0.2

  # For Form
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.21
  multi_select_flutter: ^4.1.3
  searchfield: ^0.9.0
  dropdown_button2: ^2.3.9
  simple_chips_input: ^1.2.0
  flutter_social_textfield: ^0.1.2
  flutter_advanced_switch: ^3.0.1
  readmore: ^2.2.0
  flutter_typeahead: ^4.8.0
  form_builder_extra_fields: ^10.1.0

  # For Loading / Refresh
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  overlay_support: ^2.1.0 
  loading_overlay: ^0.3.0

  # For Toast
  fluttertoast: ^8.2.2

  # For Maps
  google_maps_flutter: ^2.5.0
  map_location_picker: ^1.2.8+3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_animarker: ^3.2.0

  # For Share
  social_share: ^2.3.1
  share_plus: ^7.2.1
  clipboard: ^0.1.3

  # For Settings
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  vector_math: ^2.1.4
  open_store: ^0.5.0
  url_launcher: ^6.2.1
  theme_button: ^1.0.4
  flutter_dotenv: ^5.1.0
  map_launcher: ^3.1.0
  flutter_slidable: ^3.0.1
  flutter_keyboard_visibility: ^5.4.1
  vibration: ^1.8.4
  photo_view: ^0.14.0
  flutter_emoji: ^2.5.1
  sms_autofill: ^2.3.0 
  sms_autodetect: ^1.0.9
  path_provider: ^2.1.2
  path: ^1.8.3
  showcaseview: ^2.0.3
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  flutter_cache_manager: ^3.3.1
  screenshot: ^2.1.0
  app_links: ^6.1.4
  flutter_rating_bar: ^4.0.1
  widget_to_marker: ^1.0.4
  flutter_url_shortener: ^2.0.0
  app_tracking_transparency: ^2.0.4
  firebase_app_check: ^0.2.1+17
  firebase_analytics: ^10.8.9
  flutter_uxcam: ^2.5.4
dependency_overrides: 
  photo_manager: ^3.0.0-dev.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9

  # For Networking
  retrofit_generator: ^8.0.4

  # For Assets
  flutter_gen_runner: ^5.3.2

  # For Navigation
  auto_route_generator: ^7.3.1

  # For Model
  freezed: ^2.3.4

  # For Analyzer
  very_good_analysis: ^5.1.0

  # For Testing
  mocktail: ^1.0.0
  mocktail_image_network: ^1.0.0

flutter_gen:
  integrations:
    flutter_svg: true
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.jpg" 

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - .env.dev
    - assets/images/
    - assets/images/Stock/
    - assets/images/Other/
    - assets/images/Dark/
    - assets/images/Light/
    - assets/icons/Bold/
    - assets/icons/Broken/
    - assets/icons/Bulk/
    - assets/icons/Curved/
    - assets/icons/Light/
    - assets/icons/Light-Outline/
    - assets/icons/Logo/
    - assets/icons/Two-tone/
    - assets/icons/Social/
    - assets/icons/Hoby/
    - assets/sounds/
    - assets/lottie/
    - assets/json/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans.ttf
