#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/arda/dev/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/arda/Documents/togodo"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.1.2"
export "FLUTTER_BUILD_NUMBER=88"
export "DART_DEFINES=RkxBVk9SPXByb2R1Y3Rpb24=,RkxVVFRFUl9BUFBfRkxBVk9SPXByb2R1Y3Rpb24="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=true"
export "PACKAGE_CONFIG=/Users/arda/Documents/togodo/.dart_tool/package_config.json"
export "FLAVOR=production"
